### ISSUE TITLE
Linux Alpine not supported.

### ISSUE THREAD

**Issue by Bagietas** [MsFloofie/ArchiSteamFarm-Installer#3]
Hey, I tried your installer on my Linux Alpine and it's showing `OS type not found. If you're running GNU/Linux, please report this on GitHub!`

**Comment by MsFloofie** [comment]
Alpine Linux is not a GNU/Linux flavor.
However I suppose that the error message could be better worded.
Never tried it on Alpine until now. After some testing, it wouldn't of worked anyways. Alpine doesn't even come with bash by default or use systemd.

What failed is that it spits out `linux-musl` from `$OSTYPE`. It only checks for `linux-gnu*` in the `os_check()` part of the script. I plan to make a change for it maybe. However, for the time being, the script failed successfully
